FROM rabbitmq:management
RUN apt-get update; apt-get -y install wget

RUN wget -O /plugins/rabbitmq_delayed_message_exchange-0.0.1.ez https://bintray.com/rabbitmq/community-plugins/download_file?file_path=rabbitmq_delayed_message_exchange-0.0.1.ez

RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange